sudo: false
cache: bundler
language: ruby
addons:
  apt:
    packages:
    - libgecode-dev
rvm:
- 2.3.1
env:
  global:
  - USE_SYSTEM_GECODE=true
before_install: "gem install bundler"
bundler_args: "--binstubs=$PWD/bin --jobs 3 --retry 3"
script:
- "./bin/rake travis"
gemfile:
- test/gemfiles/chef-12.gemfile
- test/gemfiles/master.gemfile
